kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: finastra-np-demo1
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
        - podSelector: {}
